<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ShirtsSeeder extends Seeder
{
    /**
     * Run the database seeder that inserts the shirts data.
     */
    public function run(): void
    {
        $shirts = [
            [
                'title' => 'Argentina',
                'description' => 'Los Pumas',
                'category' => '',
                'price' => '74.99',
                'percent_discount' => 0,
                'sku' => '',
                'warranty' => '',
                'shipping' => '',
                'availability' => '',
                'return_policy' => '',
                'min_order_quantity' => 0,
                'thumbnail' => '',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ], 
            [
                'title' => 'Australia',
                'description' => 'The Wallabies',
                'category' => '',
                'price' => '72.95',
                'percent_discount' => 0,
                'sku' => '',
                'warranty' => '',
                'shipping' => '',
                'availability' => '',
                'return_policy' => '',
                'min_order_quantity' => 0,
                'thumbnail' => '',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ], 
            [
                'title' => 'England',
                'description' => 'Swing low, sweet chariot',
                'category' => '',
                'price' => '87.50',
                'percent_discount' => 0,
                'sku' => '',
                'warranty' => '',
                'shipping' => '',
                'availability' => '',
                'return_policy' => '',
                'min_order_quantity' => 0,
                'thumbnail' => '',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ], 
            [
                'title' => 'Fiji',
                'description' => 'Pacific Islanders',
                'category' => '',
                'price' => '69.99',
                'percent_discount' => 0,
                'sku' => '',
                'warranty' => '',
                'shipping' => '',
                'availability' => '',
                'return_policy' => '',
                'min_order_quantity' => 0,
                'thumbnail' => '',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ], 
            [
                'title' => 'France',
                'description' => 'Tous Emsemble',
                'category' => '',
                'price' => '70.75',
                'percent_discount' => 0,
                'sku' => '',
                'warranty' => '',
                'shipping' => '',
                'availability' => '',
                'return_policy' => '',
                'min_order_quantity' => 0,
                'thumbnail' => '',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ], 
            [
                'title' => 'Italy',
                'description' => 'Azzure blue',
                'category' => '',
                'price' => '58.99',
                'percent_discount' => 10,
                'sku' => '',
                'warranty' => '',
                'shipping' => '',
                'availability' => '',
                'return_policy' => '',
                'min_order_quantity' => 0,
                'thumbnail' => '',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ], 
            [
                'title' => 'Ireland',
                'description' => 'Answer Irelands call',
                'category' => '',
                'price' => '65.99',
                'percent_discount' => 0,
                'sku' => '',
                'warranty' => '',
                'shipping' => '',
                'availability' => '',
                'return_policy' => '',
                'min_order_quantity' => 0,
                'thumbnail' => '',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ], 
            [
                'title' => 'Japan',
                'description' => 'Bushido',
                'category' => '',
                'price' => '79.99',
                'percent_discount' => 0,
                'sku' => '',
                'warranty' => '',
                'shipping' => '',
                'availability' => '',
                'return_policy' => '',
                'min_order_quantity' => 0,
                'thumbnail' => '',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ], 
            [
                'title' => 'New Zealand',
                'description' => 'All Blacks Limited Edition',
                'category' => '',
                'price' => '79.99',
                'percent_discount' => 0,
                'sku' => '',
                'warranty' => '',
                'shipping' => '',
                'availability' => '',
                'return_policy' => '',
                'min_order_quantity' => 0,
                'thumbnail' => '',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ], 
            [
                'title' => 'Scotland',
                'description' => 'Oh flower of Scotland',
                'category' => '',
                'price' => '55.90',
                'percent_discount' => 0,
                'sku' => '',
                'warranty' => '',
                'shipping' => '',
                'availability' => '',
                'return_policy' => '',
                'min_order_quantity' => 0,
                'thumbnail' => '',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ], 
            [
                'title' => 'South Africa',
                'description' => 'The Springboks',
                'category' => '',
                'price' => '56.25',
                'percent_discount' => 0,
                'sku' => '',
                'warranty' => '',
                'shipping' => '',
                'availability' => '',
                'return_policy' => '',
                'min_order_quantity' => 0,
                'thumbnail' => '',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ], 
            [
                'title' => 'Wales',
                'description' => 'The Valleys',
                'category' => '',
                'price' => '69.99',
                'percent_discount' => 0,
                'sku' => '',
                'warranty' => '',
                'shipping' => '',
                'availability' => '',
                'return_policy' => '',
                'min_order_quantity' => 0,
                'thumbnail' => '',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ], 
        ];

        DB::table('shirts')->insert($shirts);
    }
}
